# config/dataset/CelebDF.yml
# -------------------------------------------------
# Cleaned CelebDB (k=120) splits on your machine
# -------------------------------------------------

# -------------------------- TRAIN ---------------------------
train_cfg:
  root: "/workspace/AAAI-Paper/Attention_Network_for_Deepfake_Detection/celebdb_clean/celebdb_splits_reduced_k120_dedup/train"
  split: "train"
  balance: True                 # use WeightedRandomSampler
  # per-video sampling (kept for consistency; folders are already capped)
  max_frames_per_video: 120
  sampling_strategy: "strided_unique"
  stride_hint: 5
  drop_near_duplicates: True
  sim_threshold: 0.985
  sim_window: 6
  return_path: False

  transforms:
    - name: Resize
      params: {height: 299, width: 299}
    - name: HorizontalFlip
      params: {p: 0.5}
    - name: Normalize
      params: {mean: [0.5, 0.5, 0.5], std: [0.5, 0.5, 0.5]}

# --------------------------- VAL ----------------------------
val_cfg:
  root: "/workspace/AAAI-Paper/Attention_Network_for_Deepfake_Detection/celebdb_clean/celebdb_splits_reduced_k120_dedup/val"
  split: "val"
  balance: False
  max_frames_per_video: 120
  sampling_strategy: "strided_unique"
  stride_hint: 5
  drop_near_duplicates: True
  sim_threshold: 0.985
  sim_window: 6
  return_path: True

  transforms:
    - name: Resize
      params: {height: 299, width: 299}
    - name: Normalize
      params: {mean: [0.5, 0.5, 0.5], std: [0.5, 0.5, 0.5]}

# --------------------------- TEST ---------------------------
test_cfg:
  root: "/workspace/AAAI-Paper/Attention_Network_for_Deepfake_Detection/celebdb_clean/celebdb_splits_reduced_k120_dedup/test"
  split: "test"
  balance: False
  max_frames_per_video: 120
  sampling_strategy: "strided_unique"
  stride_hint: 5
  drop_near_duplicates: True
  sim_threshold: 0.985
  sim_window: 6
  return_path: True

  transforms:
    - name: Resize
      params: {height: 299, width: 299}
    - name: Normalize
      params: {mean: [0.5, 0.5, 0.5], std: [0.5, 0.5, 0.5]}
