test_cfg:
  root: "/path/to/FaceForensics++_extracted"  # Update this path
  split: "test"
  balance: False
  # FaceForensics++ specific settings
  manipulation_types: ["Deepfakes", "Face2Face", "FaceSwap", "NeuralTextures"]
  compression: "c23"  # High quality compression
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
        
# Configuration for different manipulation types
deepfakes_cfg:
  root: "/path/to/FaceForensics++_extracted/Deepfakes"
  split: "test"
  balance: False
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

face2face_cfg:
  root: "/path/to/FaceForensics++_extracted/Face2Face"
  split: "test"
  balance: False
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

faceswap_cfg:
  root: "/path/to/FaceForensics++_extracted/FaceSwap"
  split: "test"
  balance: False
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]

neuraltextures_cfg:
  root: "/path/to/FaceForensics++_extracted/NeuralTextures"
  split: "test"
  balance: False
  transforms:
    - name: "Resize"
      params:
        height: 299
        width: 299
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]